<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Perusahaan_model extends CI_Model
{

    public $table = 'perusahaan';
    public $id = 'id_perusahaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_id_users($id)
    {
        $this->db->where('id_users', $id);
        return $this->db->get($this->table)->row();
    }

    function cek_data($id){
        $this->db->select('id_users');
        $this->db->where('id_users', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_perusahaan', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('nama_perusahaan', $q);
	$this->db->or_like('alamat_perusahaan', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->or_like('skala', $q);
	$this->db->or_like('no_telpon', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('bidang_usaha', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('logo', $q);
	$this->db->or_like('siup', $q);
	$this->db->or_like('npwp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function total_data() {
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_perusahaan', $q);
	$this->db->or_like('id_users', $q);
	$this->db->or_like('nama_perusahaan', $q);
	$this->db->or_like('alamat_perusahaan', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->or_like('skala', $q);
	$this->db->or_like('no_telpon', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('bidang_usaha', $q);
	$this->db->or_like('website', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('logo', $q);
	$this->db->or_like('siup', $q);
	$this->db->or_like('npwp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Perusahaan_model.php */
/* Location: ./application/models/Perusahaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-10 08:21:32 */
/* http://harviacode.com */