<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Riwayat_kerja_model extends CI_Model
{

    public $table = 'riwayat_kerja';
    public $id = 'id_pekerjaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_all_by_id2($id)
    {
        $this->db->where('id_member', $id);
        return $this->db->get($this->table)->result();
    }


    function get_all_by_id()
    {
        $idp = $this->get_id_member();
        $this->db->where('id_member', $idp);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pekerjaan', $q);
	$this->db->or_like('id_member', $q);
	$this->db->or_like('nama_perusahaan', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('masa_kerja', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($id, $limit, $start = 0, $q = NULL) {
        $this->db->where('id_member', $id);
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pekerjaan', $q);
	$this->db->or_like('id_member', $q);
	$this->db->or_like('nama_perusahaan', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('masa_kerja', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // function cek_data($id){
    //     $this->db->select('id_member');
    //     $this->db->where('id_users', $id);
    //     return $this->db->get($this->table)->row();
    // }

    function get_id_member(){
        $this->db->select('id_member');
        $id_users = $this->session->userdata('id_users');
        $this->db->where('id_users', $id_users);
        return $this->db->get('member')->row()->id_member;  
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Riwayat_kerja_model.php */
/* Location: ./application/models/Riwayat_kerja_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-10 08:21:32 */
/* http://harviacode.com */