<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sub_kejuruan_model extends CI_Model
{

    public $table = 'sub_kejuruan';
    public $id = 'id_sub_kejuruan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('kejuruan','sub_kejuruan.id_kejuruan = kejuruan.id_kejuruan');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('kejuruan','sub_kejuruan.id_kejuruan = kejuruan.id_kejuruan');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('kejuruan','sub_kejuruan.id_kejuruan = kejuruan.id_kejuruan');
        $this->db->like('id_sub_kejuruan', $q);
	$this->db->or_like('sub_kejuruan.id_kejuruan', $q);
	$this->db->or_like('nama_sub_kejuruan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('kejuruan','sub_kejuruan.id_kejuruan = kejuruan.id_kejuruan');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sub_kejuruan', $q);
	$this->db->or_like('sub_kejuruan.id_kejuruan', $q);
	$this->db->or_like('nama_sub_kejuruan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function dd_kejuruan()
    {
        // ambil data dari db
        $this->db->order_by('id_kejuruan', 'asc');
        $result = $this->db->get('kejuruan');
        
        // bikin array
        // please select berikut ini merupakan tambahan saja agar saat pertama
        // diload akan ditampilkan text please select.
        $dd[''] = 'Please Select';
        if ($result->num_rows() > 0) {
            foreach ($result->result() as $row) {
            // tentukan value (sebelah kiri) dan labelnya (sebelah kanan)
                $dd[$row->id_kejuruan] = $row->nama_kejuruan;
            }
        }
        return $dd;
    }

}

/* End of file Sub_kejuruan_model.php */
/* Location: ./application/models/Sub_kejuruan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-10 08:21:33 */
/* http://harviacode.com */